on:
  schedule:
      # Runs at 12am UTC
      - cron: '0 0 */2 * *' 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:  
  update-readme:
    name: Update Medium Articles
    runs-on: ubuntu-latest
    steps:
      - uses: wathsara/medium-blogs-readme@master
        with:
          MEDIUM_HANDLER: '@wathsara'
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: Wathsara/test-medium
          DAYS: 365
